[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{{project-name}}"
path = "src/bin/main.rs"

[dependencies]
anyhow = {workspace = true}

[dev-dependencies]
rstest = { workspace = true }
