[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01-part1"
path = "src/bin/part1.rs"

[[bin]]
name = "day01-part2"
path = "src/bin/part2.rs"

[dependencies]
anyhow = {workspace = true}

[dev-dependencies]
rstest = { workspace = true }
