[package]
name = "day06"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day06"
path = "src/bin/main.rs"

[dependencies]
anyhow = {workspace = true}

[dev-dependencies]
rstest = { workspace = true }
