[package]
name = "day03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day03"
path = "src/bin/main.rs"

[dependencies]
anyhow = { workspace = true }
nom = { workspace = true }
regex = "1.11.1"

[dev-dependencies]
rstest = { workspace = true }
